### ISSUE TITLE
Problem with auto-replies

### ISSUE THREAD

**Issue by ivanmon** [reneeb/otrs-MultiSMTP#7] opened 2015-10-15 20:44 UTC
Hi reneeb,
Thanks for you work, but I ran into a problem with the auto-replies.
I using this on OTRS 3.3.12 (Multismtp 3.3.3) with three mail accounts and different auto-replies .
In two mails do not work auto-replies.
Errors:
Thu Oct 15 13:12:04 2015 error OTRS-RPC-10 Impossible to send message to: xxx@xxx.ru .
Thu Oct 15 13:12:04 2015 info OTRS-RPC-10 Error sending message
Thu Oct 15 13:12:04 2015 error OTRS-RPC-10 Can't use from '=?UTF-8?Q?=D0=9F=D0=BE=D0=B4=D0=B4=D0=B5=D1=80=D0=B6=D0=BA=D0=B0=20?=': 5035.5.4 Error: send AUTH command first.
Thu Oct 15 13:12:04 2015 error OTRS-RPC-10 Need Address!

If I unplag the expansion , the problem disappears. Please help me to cope with this problem!

**Comment by reneeb** [comment] 2015-10-16 08:54
This is a duplicate of #5 . I'll close this issue and work on #5 . I'll have a look at it this weekend...

**Comment by ivanmon** [comment] 2015-10-16 15:08
Hey there!
So, the problem have been solved. We've "recreated" the e-mail's in the mail's settings > email address.
And we've also chenged into new one's int the autoreplies > line. Thanks anyway!

**Comment by reneeb** [comment] 2016-04-26 12:45
There was a bug with regard to auto-responses. This should be fixed in the latest version.

**Closed by reneeb** 2016-04-26 12:45 UTC
